"use client";

// K003 historical export controls. The browser selects already committed
// simulator data and downloads backend-generated bytes; it never advances the
// engine, aggregates telemetry, or creates a dataset itself.

import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import {
  EXPORT_FORMATS,
  EXPORT_INTERVALS,
  HistoricalExportError,
  chooseHistoricalRun,
  dateTimeLocalToUtc,
  fetchExportFile,
  fetchHistoricalRuns,
  utcToDateTimeLocal,
  validateExportWindow,
  type ExportFormat,
  type ExportIntervalSeconds,
  type HistoricalRun,
} from "../lib/historical-export";

type CatalogPhase = "loading" | "ready" | "error";

const fieldClass = "sim-field";

const intervalLabels: Record<ExportIntervalSeconds, string> = {
  60: "1 minute",
  300: "5 minutes",
  600: "10 minutes",
  900: "15 minutes",
  1800: "30 minutes",
  3600: "60 minutes",
};

function displayUtc(value: string): string {
  return new Date(value).toLocaleString("en-GB", {
    timeZone: "UTC",
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  });
}

function errorText(error: unknown): string {
  if (error instanceof HistoricalExportError) {
    const location = error.field ? ` (${error.field})` : "";
    return `${error.message}${location} [${error.code}]`;
  }
  return error instanceof Error ? error.message : "Unknown export error.";
}

export default function HistoricalExportPanel({
  backendUrl,
  currentRunId,
}: {
  backendUrl: string;
  currentRunId: string | null;
}) {
  const [catalogPhase, setCatalogPhase] = useState<CatalogPhase>("loading");
  const [runs, setRuns] = useState<HistoricalRun[] | null>(null);
  const [catalogError, setCatalogError] = useState<string | null>(null);
  const [catalogRefreshing, setCatalogRefreshing] = useState(false);
  const [selectedRunId, setSelectedRunId] = useState<string | null>(null);
  const [format, setFormat] = useState<ExportFormat>("json");
  const [intervalSeconds, setIntervalSeconds] = useState<ExportIntervalSeconds>(60);
  const [windowDraft, setWindowDraft] = useState<{
    runId: string;
    from: string;
    to: string;
  } | null>(null);
  const [downloading, setDownloading] = useState(false);
  const [downloadStatus, setDownloadStatus] = useState<string | null>(null);
  const [downloadError, setDownloadError] = useState<string | null>(null);

  const mounted = useRef(true);
  const runsRef = useRef<HistoricalRun[] | null>(null);
  const currentRunIdRef = useRef(currentRunId);
  const catalogGeneration = useRef(0);
  const catalogInFlight = useRef<AbortController | null>(null);
  const exportInFlight = useRef<AbortController | null>(null);
  const downloadGuard = useRef(false);
  const explicitSelection = useRef(false);
  const previousCurrentRun = useRef(currentRunId);
  const selectionVersion = useRef(0);

  const retainObjectUrl = useCallback((url: string) => {
    // Each download owns an independent lifetime. Keeping this well beyond the
    // click avoids revoking a previous/large file while the browser is writing
    // it; the browser reclaims naturally if the document unloads first.
    window.setTimeout(() => URL.revokeObjectURL(url), 5 * 60_000);
  }, []);

  const refreshRuns = useCallback(async () => {
    if (catalogInFlight.current) return;
    const controller = new AbortController();
    const generation = ++catalogGeneration.current;
    catalogInFlight.current = controller;
    setCatalogRefreshing(true);
    if (!runsRef.current) setCatalogPhase("loading");
    try {
      const nextRuns = await fetchHistoricalRuns(
        backendUrl,
        fetch,
        controller.signal,
      );
      if (!mounted.current || generation !== catalogGeneration.current) return;
      runsRef.current = nextRuns;
      setRuns(nextRuns);
      setCatalogError(null);
      setCatalogPhase("ready");
      setSelectedRunId((previous) => {
        if (explicitSelection.current && previous !== null) {
          const preserved = nextRuns.find((run) => run.runId === previous);
          if (preserved) return preserved.runId;
        }
        return chooseHistoricalRun(nextRuns, currentRunIdRef.current, previous)?.runId ?? null;
      });
    } catch (error) {
      if (!mounted.current || generation !== catalogGeneration.current || controller.signal.aborted) return;
      setCatalogError(errorText(error));
      if (!runsRef.current) setCatalogPhase("error");
    } finally {
      if (catalogInFlight.current === controller) catalogInFlight.current = null;
      if (mounted.current && generation === catalogGeneration.current) setCatalogRefreshing(false);
    }
  }, [backendUrl]);

  // Fetch once per backend identity, never once per live poll or current-run id.
  useEffect(() => {
    mounted.current = true;
    const timer = window.setTimeout(() => void refreshRuns(), 0);
    return () => {
      mounted.current = false;
      catalogGeneration.current += 1;
      window.clearTimeout(timer);
      catalogInFlight.current?.abort();
      catalogInFlight.current = null;
      exportInFlight.current?.abort();
      exportInFlight.current = null;
    };
  }, [refreshRuns]);

  // A reset/new run becomes the default selection, but an explicit historical
  // choice remains stable during ordinary catalog refreshes.
  useEffect(() => {
    currentRunIdRef.current = currentRunId;
    if (previousCurrentRun.current !== currentRunId) {
      previousCurrentRun.current = currentRunId;
      explicitSelection.current = false;
      selectionVersion.current += 1;
      exportInFlight.current?.abort();
      exportInFlight.current = null;
      setSelectedRunId(currentRunId);
      setWindowDraft(null);
      setDownloadError(null);
      setDownloadStatus(null);
    }
  }, [currentRunId]);

  const selectedRun = runs?.find((run) => run.runId === selectedRunId) ?? null;
  const coverageStart = selectedRun?.committedStartUtc ?? null;
  const coverageEnd = selectedRun?.committedEndUtc ?? null;
  // A draft belongs to one run. Selecting another run automatically restores
  // that run's committed-coverage defaults without a state-setting effect.
  const fromLocal = windowDraft?.runId === selectedRunId
    ? windowDraft.from
    : coverageStart
      ? utcToDateTimeLocal(coverageStart)
      : "";
  const toLocal = windowDraft?.runId === selectedRunId
    ? windowDraft.to
    : coverageEnd
      ? utcToDateTimeLocal(coverageEnd)
      : "";

  const fromUtc = fromLocal ? dateTimeLocalToUtc(fromLocal) : null;
  const toUtc = toLocal ? dateTimeLocalToUtc(toLocal) : null;
  const hasCoverage = Boolean(
    selectedRun &&
      selectedRun.committedIntervalCount > 0 &&
      selectedRun.committedStartUtc !== null &&
      selectedRun.committedEndUtc !== null,
  );
  const windowError = !hasCoverage
    ? null
    : !fromLocal
      ? "Start is required."
      : fromUtc === null
        ? "Enter a valid start UTC date and time."
        : !toLocal
          ? "End is required."
          : toUtc === null
            ? "Enter a valid end UTC date and time."
            : validateExportWindow(fromUtc, toUtc);
  const canDownload = Boolean(
    selectedRun?.exportable &&
      hasCoverage &&
      fromUtc &&
      toUtc &&
      !windowError &&
      !catalogRefreshing &&
      !downloading,
  );

  function selectRun(runId: string) {
    explicitSelection.current = true;
    selectionVersion.current += 1;
    setSelectedRunId(runId);
    setWindowDraft(null);
    setDownloadError(null);
    setDownloadStatus(null);
  }

  async function download(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (downloadGuard.current || !selectedRun || !canDownload || !fromUtc || !toUtc) return;
    downloadGuard.current = true;
    setDownloading(true);
    setDownloadError(null);
    setDownloadStatus("Preparing export…");

    const controller = new AbortController();
    exportInFlight.current = controller;
    const requestedVersion = selectionVersion.current;
    try {
      const file = await fetchExportFile(
        backendUrl,
        {
          runId: selectedRun.runId,
          format,
          intervalSeconds,
          fromUtc,
          toUtc,
        },
        fetch,
        controller.signal,
      );
      if (!mounted.current || requestedVersion !== selectionVersion.current) return;

      const url = URL.createObjectURL(file.blob);
      const anchor = document.createElement("a");
      anchor.href = url;
      anchor.download = file.filename;
      anchor.rel = "noopener";
      anchor.style.display = "none";
      try {
        document.body.appendChild(anchor);
        anchor.click();
      } catch (error) {
        URL.revokeObjectURL(url);
        throw error;
      } finally {
        anchor.remove();
      }
      retainObjectUrl(url);
      setDownloadStatus(`${format.toUpperCase()} download started: ${file.filename}`);
    } catch (error) {
      if (!mounted.current || controller.signal.aborted) return;
      setDownloadStatus(null);
      setDownloadError(errorText(error));
    } finally {
      if (exportInFlight.current === controller) exportInFlight.current = null;
      downloadGuard.current = false;
      if (mounted.current) setDownloading(false);
    }
  }

  const staleCatalog = catalogPhase === "ready" && catalogError !== null;

  return (
    <section
      aria-labelledby="historical-export-title"
      className="sim-panel sim-export-panel"
    >
      <div className="sim-panel-head">
        <div>
          <h2 id="historical-export-title" className="sim-panel-title">
            Historical data export
          </h2>
          <p className="sim-panel-description">
            Download committed synthetic simulator readings for auditor import.
          </p>
        </div>
        <button
          type="button"
          onClick={() => void refreshRuns()}
          disabled={catalogRefreshing || downloading}
          className="sim-btn sim-btn-ghost"
        >
          {catalogRefreshing ? "Refreshing…" : "Refresh runs"}
        </button>
      </div>

      {catalogPhase === "loading" && (
        <p role="status" aria-live="polite" className="sim-export-help">
          Loading historical runs…
        </p>
      )}
      {catalogPhase === "error" && (
        <div role="alert" className="sim-error sim-export-error">
          <p><strong>Historical runs unavailable</strong></p>
          <p>{catalogError}</p>
        </div>
      )}
      {staleCatalog && (
        <div role="alert" className="sim-warn sim-export-warning">
          Showing the last successful run catalog. Refresh failed: {catalogError}
        </div>
      )}
      {catalogPhase === "ready" && runs?.length === 0 && (
        <p className="sim-export-help">No simulation runs are available.</p>
      )}

      {runs && runs.length > 0 && (
        <form onSubmit={download} className="sim-export-form">
          <fieldset disabled={catalogRefreshing || downloading} className="sim-export-fieldset">
            <legend className="sr-only">Historical export selection</legend>
            <div>
              <label htmlFor="export-run" className="sim-label">
                Historical run
              </label>
              <select
                id="export-run"
                value={selectedRunId ?? ""}
                onChange={(event) => selectRun(event.target.value)}
                aria-describedby="export-coverage"
                className={fieldClass}
              >
                {runs.map((run) => {
                  const coverage = run.committedIntervalCount
                    ? `${run.committedIntervalCount.toLocaleString()} committed rows`
                    : "no committed readings";
                  return (
                    <option key={run.runId} value={run.runId}>
                      {run.runId} — {coverage}
                      {run.exportable ? "" : " — unavailable"}
                    </option>
                  );
                })}
              </select>
            </div>

            <div id="export-coverage" className="sim-export-coverage">
              {selectedRun ? (
                <>
                  <p>
                    <span className="font-medium">Status:</span> {selectedRun.status}; {selectedRun.committedIntervalCount.toLocaleString()} committed interval rows.
                  </p>
                  <p>
                    <span className="font-medium">Committed coverage (UTC):</span>{" "}
                    {selectedRun.committedStartUtc && selectedRun.committedEndUtc
                      ? `${displayUtc(selectedRun.committedStartUtc)} to ${displayUtc(selectedRun.committedEndUtc)} (end exclusive)`
                      : "none"}
                  </p>
                  <p className="mt-1">
                    Coverage comes only from persisted committed rows. The active run&apos;s unfinished minute and simulated time after the last committed row are not exported.
                  </p>
                  {!selectedRun.exportable && (
                    <p className="sim-export-warning-text">
                      This run cannot be exported: {selectedRun.unavailableReason ?? "backend unavailable"}.
                    </p>
                  )}
                </>
              ) : (
                "Select a run."
              )}
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <div>
                <label htmlFor="export-from" className="sim-label">
                  Start (UTC, inclusive)
                </label>
                <input
                  id="export-from"
                  type="datetime-local"
                  step="1"
                  required
                  value={fromLocal}
                  onChange={(event) => {
                    if (selectedRunId) {
                      setWindowDraft({ runId: selectedRunId, from: event.target.value, to: toLocal });
                    }
                  }}
                  aria-invalid={windowError !== null}
                  aria-describedby={windowError ? "export-window-help export-window-error" : "export-window-help"}
                  className={fieldClass}
                />
              </div>
              <div>
                <label htmlFor="export-to" className="sim-label">
                  End (UTC, exclusive)
                </label>
                <input
                  id="export-to"
                  type="datetime-local"
                  step="1"
                  required
                  value={toLocal}
                  onChange={(event) => {
                    if (selectedRunId) {
                      setWindowDraft({ runId: selectedRunId, from: fromLocal, to: event.target.value });
                    }
                  }}
                  aria-invalid={windowError !== null}
                  aria-describedby={windowError ? "export-window-help export-window-error" : "export-window-help"}
                  className={fieldClass}
                />
              </div>
            </div>
            <p id="export-window-help" className="sim-export-help">
              Inputs are explicitly interpreted as UTC. The end is exclusive. Coarser intervals aggregate committed one-minute readings and do not create finer detail.
            </p>
            {windowError && (
              <p id="export-window-error" role="alert" className="sim-export-error">
                {windowError}
              </p>
            )}

            <div className="grid gap-4 sm:grid-cols-2">
              <div>
                <label htmlFor="export-format" className="sim-label">
                  Format
                </label>
                <select
                  id="export-format"
                  value={format}
                  onChange={(event) => setFormat(event.target.value as ExportFormat)}
                  className={fieldClass}
                >
                  {EXPORT_FORMATS.map((value) => (
                    <option key={value} value={value}>
                      {value.toUpperCase()}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label htmlFor="export-interval" className="sim-label">
                  Aggregation interval
                </label>
                <select
                  id="export-interval"
                  value={intervalSeconds}
                  onChange={(event) => setIntervalSeconds(Number(event.target.value) as ExportIntervalSeconds)}
                  className={fieldClass}
                >
                  {EXPORT_INTERVALS.map((value) => (
                    <option key={value} value={value}>
                      {intervalLabels[value]}
                    </option>
                  ))}
                </select>
              </div>
            </div>
          </fieldset>

          <div className="flex flex-wrap items-center gap-3">
            <button
              type="submit"
              disabled={!canDownload}
              className="sim-btn sim-btn-primary"
            >
              {downloading ? "Preparing download…" : `Download ${format.toUpperCase()}`}
            </button>
            {!hasCoverage && selectedRun && (
              <span className="sim-export-help">
                This run has no committed readings to export yet.
              </span>
            )}
          </div>
          {downloadStatus && (
            <p role="status" aria-live="polite" className="sim-export-success break-all">
              {downloadStatus}
            </p>
          )}
          {downloadError && (
            <p role="alert" className="sim-export-error break-words">
              {downloadError}
            </p>
          )}
        </form>
      )}
    </section>
  );
}
